### ISSUE TITLE
Issueってこんな感じの機能

### ISSUE THREAD

**Issue by ayaha401** [amakasuzirofight/zenjectTest#1]
# Issueですること
プログラムの議論をしたり、修正案を出したりするよ

# 例えば
https://github.com/amakasuzirofight/zenjectTest/blob/eef7bb1028fa7f31e93f337cf14b56dc70289696/ZenjectTest/Assets/CallHOge.cs#L5
`CallHOge`はクラス名はおかしい気がする
```C#
public class CallHoge : MonoBehaviour
```
にするべきだと思う

こんな感じに使えたり、
https://github.com/amakasuzirofight/zenjectTest/blob/eef7bb1028fa7f31e93f337cf14b56dc70289696/ZenjectTest/Assets/CallHOge.cs#L16-L26

こんな感じに一行だけではなくて複数行を表示もできる。

青色の場所をクリックするとプログラムに飛べる。

# これで何するの？
今までのように口頭でプログラムの修正箇所を使えたり議論をしていると忘れてしまったりするのでこのIssueを使って修正箇所をリストアップできるようにして使うよ

**全部読めたらこのIssueの下に返信をしてみて**

**Comment by amakasuzirofight** [comment]
よみました

**Comment by ayaha401** [comment]
問題や議論が終了したら**Close with comment**を押してIssueを閉じるよ。
閉じる＝議論終了（もしくは問題解決）ってことね
